-- Run this in Supabase SQL Editor: https://supabase.com/dashboard/project/huuvhqekxufvnrdoiokc/sql

-- Attractions (participants in the parade)
CREATE TABLE attractions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nome text NOT NULL,
  tema text NOT NULL,
  event_date date NOT NULL,
  ordem int DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

-- Judges (anonymous codes generated by admin)
CREATE TABLE judges (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code text UNIQUE NOT NULL,
  label text,
  created_at timestamptz DEFAULT now()
);

-- Votes
CREATE TABLE votes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  attraction_id uuid REFERENCES attractions(id) ON DELETE CASCADE,
  judge_id uuid REFERENCES judges(id) ON DELETE CASCADE,
  adesao_tema int CHECK (adesao_tema BETWEEN 1 AND 5),
  criatividade int CHECK (criatividade BETWEEN 1 AND 5),
  performance int CHECK (performance BETWEEN 1 AND 5),
  total int GENERATED ALWAYS AS (adesao_tema + criatividade + performance) STORED,
  submitted_at timestamptz DEFAULT now(),
  UNIQUE(attraction_id, judge_id)
);

-- App settings
CREATE TABLE settings (
  key text PRIMARY KEY,
  value text NOT NULL
);

INSERT INTO settings (key, value) VALUES
  ('result_revealed', 'false'),
  ('active_event', '2026-05-05'),
  ('voting_open', 'true');

-- RLS: enable on all tables
ALTER TABLE attractions ENABLE ROW LEVEL SECURITY;
ALTER TABLE judges ENABLE ROW LEVEL SECURITY;
ALTER TABLE votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

-- Attractions: anyone can read, only service_role can write
CREATE POLICY "attractions_read" ON attractions FOR SELECT USING (true);

-- Judges: anyone can read (to validate code), only service_role can write
CREATE POLICY "judges_read" ON judges FOR SELECT USING (true);

-- Votes: judges can insert/update their own votes; nobody can read individual votes (only aggregated via API)
CREATE POLICY "votes_insert" ON votes FOR INSERT WITH CHECK (true);
CREATE POLICY "votes_update" ON votes FOR UPDATE USING (true);

-- Settings: anyone can read
CREATE POLICY "settings_read" ON settings FOR SELECT USING (true);

-- Enable realtime on votes and settings
ALTER PUBLICATION supabase_realtime ADD TABLE votes;
ALTER PUBLICATION supabase_realtime ADD TABLE settings;
